import React from "react";
import {
  LegalLayout, LegalHeader, LegalCard, LegalSection, Bulleted, Footer,
} from ".";

// Types & Config used by consumers
export type Jurisdiction = {
  country: string;
  courts: string;
};

export interface LegalConfig {
  appName: string;
  serviceProvider: string;
  effectiveDate: string;
  contactEmail: string;
  jurisdiction: Jurisdiction;
}

// ----- Clause components -----
export function AcceptanceOfTerms( { appName }: { appName: string } ) {
  return (
    <LegalSection title="1) Acceptance of Terms">
      <p>
        By accessing, downloading, installing, or using the { appName } application (&ldquo;Application&rdquo;), you agree to be bound by these Terms &amp; Conditions. If you do not agree, please do not use the Application.
      </p>
    </LegalSection>
  );
}

export function UseOfApplication() {
  return (
    <LegalSection title="2) Use of the Application">
      <Bulleted
        items={ [
          <>The Application is provided free of charge for educational purposes.</>,
          <>You agree not to copy, modify, reverse engineer, decompile, attempt to extract the source code of, or create derivative works based on the Application.</>,
          <>All intellectual property rights (including copyrights, trademarks, and database rights) in and to the Application remain the property of the Service Provider.</>,
        ] }
      />
    </LegalSection>
  );
}

export function EducationalDisclaimer() {
  return (
    <LegalSection title="3) Educational Disclaimer">
      <p>
        The Application provides Islamic audio content for learning and reference. While efforts are made to ensure accuracy, the Service Provider does not guarantee that all content is complete, error-free, or represents the only valid scholarly opinion. Users are encouraged to consult qualified scholars for religious rulings or further guidance.
      </p>
    </LegalSection>
  );
}

export function PrivacyNoData() {
  return (
    <LegalSection title="4) Privacy Policy (No Data Collected)">
      <p>
        <strong>We do not collect, store, or process any personal data from users within the Application.</strong>
      </p>
      <p>Because we do not collect data, we do not sell or share personal information with third parties.</p>
      <h3 className="mt-4 text-base font-semibold">Third-Party Services &amp; Device/Store Data</h3>
      <p>
        Any data generated by your device, operating system, network, app store, or platform (e.g., bandwidth usage, crash information collected by the OS or store) is outside the control of the Service Provider and is governed by those parties’ terms and policies.
      </p>
    </LegalSection>
  );
}

export function PrivacyAndCrashData() {
  return (
    <LegalSection title="4) Privacy Policy & Crash Data">
      <p>
        We do not automatically collect personal data such as names or
        contact details during normal use of the Application.
      </p>

      <p>
        <strong>Exception:</strong> If you voluntarily provide information
        (for example, your email address when reporting an issue or
        suggesting an edit), that data will be used solely for the purpose
        of responding to your request and will not be shared with third
        parties for marketing or unrelated purposes.
      </p>

      <p>
        In order to maintain stability and improve performance, the
        Application also uses <strong>Google Crashlytics</strong> to
        automatically collect technical information when the app crashes.
        This data may include device type, operating system version,
        anonymized identifiers, crash logs, and the state of the
        Application at the time of failure.
      </p>

      <p>
        This crash data is used solely for diagnosing problems and
        improving app reliability. It is not used for marketing or profiling
        and does not include personally identifiable information.
      </p>

      <h3 className="mt-4 text-base font-semibold">
        Third-Party Services &amp; Device/Store Data
      </h3>
      <p>
        Crash data is transmitted to and managed by Google via Crashlytics,
        subject to Google’s own privacy policies. In addition, any data
        generated by your device, operating system, network, app store, or
        platform (e.g., bandwidth usage, diagnostic reports collected by the
        OS or store) is outside the control of the Service Provider and is
        governed by those parties’ terms and policies.
      </p>
    </LegalSection>
  );
}


export function InternetAndDeviceUsage() {
  return (
    <LegalSection title="5) Internet &amp; Device Usage">
      <Bulleted
        items={ [
          <>Some features may require an active internet connection. The Service Provider is not responsible if the Application does not function due to lack of connectivity or data allowance.</>,
          <>If you use the Application outside a Wi‑Fi area, your mobile network provider may charge you for data usage (including roaming charges).</>,
          <>Maintaining your device’s charge, functionality, and compatibility is your responsibility.</>,
        ] }
      />
    </LegalSection>
  );
}

export function UpdatesAndAvailability() {
  return (
    <LegalSection title="6) Updates &amp; Availability">
      <Bulleted
        items={ [
          <>The Service Provider may update the Application to improve performance or content, and you agree to accept such updates when available.</>,
          <>We do not guarantee the Application will always remain available or compatible with all future operating system versions or devices.</>,
        ] }
      />
    </LegalSection>
  );
}

export function LimitationOfLiability() {
  return (
    <LegalSection title="7) Limitation of Liability">
      <p>
        To the maximum extent permitted by law, the Service Provider is not liable for any direct, indirect, incidental, special, consequential, or exemplary damages arising from your use of or inability to use the Application. Functionality may rely on third-party sources or services, and uninterrupted, error-free operation is not guaranteed.
      </p>
    </LegalSection>
  );
}

export function TerminationClause() {
  return (
    <LegalSection title="8) Termination">
      <p>
        The Service Provider may discontinue, suspend, or restrict access to the Application at any time. Where reasonable, notice will be provided. Upon termination, you must stop using the Application and, if applicable, delete it from your device.
      </p>
    </LegalSection>
  );
}

export function GoverningLaw( { jurisdiction }: { jurisdiction: Jurisdiction } ) {
  return (
    <LegalSection title="9) Governing Law &amp; Jurisdiction">
      <p>
        These Terms &amp; Conditions are governed by and construed in accordance with the laws of the <strong>{ jurisdiction.country }</strong>. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of { jurisdiction.courts }.
      </p>
    </LegalSection>
  );
}

export function ChangesNotice() {
  return (
    <LegalSection title="10) Changes to These Terms &amp; Policy">
      <p>
        We may update these Terms &amp; Conditions and/or the Privacy Policy from time to time. Updates will be posted on this page or within the Application. Please review this page periodically for changes. Your continued use of the Application after changes constitutes acceptance of the updated terms.
      </p>
    </LegalSection>
  );
}

export function ContactUs( { email }: { email: string } ) {
  return (
    <LegalSection title="11) Contact Us">
      <p>
        If you have questions or suggestions, contact us at: <a className="underline" href={ `mailto:${email}` }>{ email }</a>
      </p>
    </LegalSection>
  );
}

// ----- Composed Page (uses sections.tsx) -----
export function LegalPage( { cfg }: { cfg: LegalConfig } ) {
  return (
    <LegalLayout>
      <LegalHeader
        serviceProvider={ cfg.serviceProvider }
        appName={ cfg.appName }
        effectiveDate={ cfg.effectiveDate }
      />

      <LegalCard>
        <p>
          <strong>Application:</strong> { cfg.appName }
        </p>
        <p>
          <strong>Service Provider:</strong> { cfg.serviceProvider }
        </p>
        <p className="text-slate-600 text-sm">
          By downloading or using the Application, you agree to the Terms &amp; Conditions below. Please read them carefully.
        </p>
      </LegalCard>

      <AcceptanceOfTerms appName={ cfg.appName } />
      <UseOfApplication />
      <EducationalDisclaimer />
      <PrivacyAndCrashData />
      <InternetAndDeviceUsage />
      <UpdatesAndAvailability />
      <LimitationOfLiability />
      <TerminationClause />
      <GoverningLaw jurisdiction={ cfg.jurisdiction } />
      <ChangesNotice />
      <ContactUs email={ cfg.contactEmail } />
      <Footer serviceProvider={ cfg.serviceProvider } />
    </LegalLayout>
  );
}
